"""split submission files into submission_files (1NF)

Revision ID: 7a2a4924f9e5
Revises: 33732b012934
Create Date: 2026-06-23 23:11:01.029016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2a4924f9e5'
down_revision: Union[str, None] = '33732b012934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['lesson_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_files_id'), 'submission_files', ['id'], unique=False)
    # Переносим существующие файлы в нормализованную таблицу до удаления колонки.
    op.execute(
        "INSERT INTO submission_files (submission_id, file_path) "
        "SELECT id, file_path FROM lesson_submissions WHERE file_path IS NOT NULL"
    )
    op.drop_column('lesson_submissions', 'file_path')


def downgrade() -> None:
    """Downgrade schema."""
    # Возвращаем колонку (временно допускающую NULL), наполняем одним файлом на работу.
    op.add_column(
        'lesson_submissions',
        sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    )
    op.execute(
        "UPDATE lesson_submissions AS ls SET file_path = ("
        "SELECT sf.file_path FROM submission_files sf "
        "WHERE sf.submission_id = ls.id ORDER BY sf.id LIMIT 1)"
    )
    # Работы без файлов: заглушка, чтобы удовлетворить исходный NOT NULL.
    op.execute("UPDATE lesson_submissions SET file_path = '' WHERE file_path IS NULL")
    op.alter_column('lesson_submissions', 'file_path', nullable=False)
    op.drop_index(op.f('ix_submission_files_id'), table_name='submission_files')
    op.drop_table('submission_files')
